name: toy-diffusion
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - jupyter=1.0.*
  - numpy=1.24.*
  - pytorch=2.0.*
  - pytorch-cuda=11.7
  - seaborn=0.12.*
  - scikit-learn=1.2.*
